### PR TITLE
Fix a bug: division is slow in some cases

### PR DESCRIPTION
**Pull request by yangby-cryptape**
- [x] Fix bug: in division, when borrow a higher unit, do not forget check if the higher unit was reduced to zero after subtraction.

  The reason was written in [this comment](https://github.com/cryptape/rust-numext/issues/34#issuecomment-476687930).

- [x] Fix bug: in division, when doing estimate is too cautious, so the estimated quotient is too small each time, led to an overflow.

  The reason was written in [this comment](https://github.com/cryptape/rust-numext/issues/36#issuecomment-476944558).

### CODE REVIEW

**Comment by mohanson** [comment]
New bugs happened. 

```rs
use numext_fixed_uint::U4096;

fn main() {
    let a = U4096::from_dec_str("77207453359070457604620928442586248569527320043595348948921733518358535471105").unwrap();
    let b = U4096::from_dec_str("115792089237316195423570985008687907853269984665640564039457584007913129639936").unwrap();

    let r1 = &a * &a;
    println!("{}", r1);

    let r2 = r1 % b;
    println!("{}", r2);
}
```

```sh

thread 'test_state_work' panicked at 'attempt to add with overflow'
```

**Comment by mohanson** [comment]
Build failed with message 

```sh
error[E0425]: cannot find value `of` in this scope
  --> C:\Users\mohan\.cargo\git\checkouts\rust-numext-836c791cc312aa11\cfab40d\fixed-uint\src\lib.rs:11:1
   |
11 | / numext_constructor::construct_fixed_uints!(
12 | |     U128 {
13 | |         size = 128,
14 | |     },
...  |
41 | |     },
42 | | );
   | |__^ not found in this scope
```

**Comment by yangby-cryptape** [comment]
That is not my fault, no matter I push which commit, travis ci always run a wrong commit.

I have passed all test in my laptop.

**Comment by yangby-cryptape** [comment]
[The difference between commit-1c32953b and commit-f898c84](https://github.com/cryptape/rust-numext/compare/1c32953b8ab4564db2ac6a665f6772ad85031fd6..f898c84ff9cd2c9412ce6fecb00f4eaabb80ab92) is nothing.

But [commit-1c32953b failed in clippy](https://github.com/cryptape/rust-numext/runs/85876261), and [commit-f898c84 passed](https://travis-ci.com/cryptape/rust-numext/builds/105947577).

Just a bug of Travis CI.

**Pull request merged**
